from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path
from dataclasses import dataclass


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────
def die(msg: str) -> None:
    print(f"[ERROR] {msg}")
    raise SystemExit(1)


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def default_site_name(domain: str) -> str:
    """
    Convert domain to a clean default brand/site name.
    Examples:
      denkengewinnen.com -> Denkengewinnen
      zahnarzt-jaghsi.de -> Zahnarzt Jaghsi
    """
    domain = domain.strip().lower()

    # take first label only (before first dot)
    host = domain.split(".", 1)[0]

    # normalize separators
    host = host.replace("_", " ").replace("-", " ")

    # title-case words
    return " ".join(w.capitalize() for w in host.split() if w)


# ─────────────────────────────────────────────
# Args model
# ─────────────────────────────────────────────
@dataclass
class EnvArgs:
    domain: str
    port: int
    project_root_base: Path
    app_module: str
    site_name: str | None
    meta_description: str
    company_email: str | None
    company_address: str
    og_image: str | None
    secret_key: str | None
    force: bool
    link_systemd: bool
    restart: bool


# ─────────────────────────────────────────────
# Core logic
# ─────────────────────────────────────────────
def write_env_file(a: EnvArgs) -> Path:
    domain = a.domain.strip().lower()
    project_dir = a.project_root_base / domain
    env_path = project_dir / ".env"

    project_dir.mkdir(parents=True, exist_ok=True)

    if env_path.exists() and not a.force:
        die(f"{env_path} already exists (use --force to overwrite)")

    content = f"""###############################################
#  {domain} – Production Environment
#  Generated by: webapp env
###############################################

ENV=production
DEBUG=false

PORT={a.port}
APP_MODULE="{a.app_module}"

SITE_NAME="{a.site_name or default_site_name(domain)}"
DOMAIN="{domain}"

DEFAULT_META_DESCRIPTION="{a.meta_description}"
DEFAULT_OG_IMAGE="{a.og_image or ""}"

COMPANY_EMAIL="{a.company_email or ""}"
COMPANY_ADDRESS="{a.company_address}"

SECRET_KEY="{a.secret_key or ""}"
"""

    env_path.write_text(content.strip() + "\n", encoding="utf-8")
    os.chmod(env_path, 0o600)

    return env_path


def link_systemd_env(domain: str, env_path: Path) -> Path:
    systemd_env = Path("/etc/webapp") / f"{domain}.env"
    systemd_env.parent.mkdir(parents=True, exist_ok=True)

    if systemd_env.exists() or systemd_env.is_symlink():
        systemd_env.unlink()

    systemd_env.symlink_to(env_path)
    return systemd_env


def restart_service(domain: str) -> None:
    run(["systemctl", "restart", f"webapp@{domain}"])


# ─────────────────────────────────────────────
# CLI entry
# ─────────────────────────────────────────────
def main() -> None:
    p = argparse.ArgumentParser(
        prog="webapp env",
        description="Generate production .env for a webapp",
    )

    p.add_argument("--domain", required=True)
    p.add_argument("--port", type=int, required=True)
    p.add_argument("--project-root", default="/var/www")
    p.add_argument("--app-module", default="app.main:app")

    p.add_argument("--site-name")
    p.add_argument("--meta-description", default="Modern FastAPI website.")
    p.add_argument("--company-email")
    p.add_argument("--company-address", default="")
    p.add_argument("--og-image")
    p.add_argument("--secret-key")

    p.add_argument("--force", action="store_true")
    p.add_argument("--link-systemd", action="store_true",
                   help="Symlink .env to /etc/webapp/<domain>.env")
    p.add_argument("--restart", action="store_true",
                   help="Restart systemd service after writing env")

    args = p.parse_args()

    if os.geteuid() != 0:
        die("Please run as root (sudo).")

    a = EnvArgs(
        domain=args.domain,
        port=args.port,
        project_root_base=Path(args.project_root),
        app_module=args.app_module,
        site_name=args.site_name,
        meta_description=args.meta_description,
        company_email=args.company_email,
        company_address=args.company_address,
        og_image=args.og_image,
        secret_key=args.secret_key,
        force=args.force,
        link_systemd=args.link_systemd,
        restart=args.restart,
    )

    # 1) write env
    env_path = write_env_file(a)
    print(f"[webapp] ✅ Written: {env_path}")
    print("[webapp] ✅ Permissions: 600")

    # 2) link systemd (optional)
    if a.link_systemd:
        systemd_env = link_systemd_env(a.domain, env_path)
        print(f"[webapp] 🔗 Linked systemd env: {systemd_env}")

    # 3) restart service (optional)
    if a.restart:
        print(f"[webapp] 🔁 Restarting systemd service: webapp@{a.domain}")
        restart_service(a.domain)


if __name__ == "__main__":
    main()
